### ISSUE TITLE
An issue with the first demo

### ISSUE THREAD

**Issue by orbitbyrd** [KevinDockx/BuildingRESTfulAPIAspNetCore3#3]
There is no controller in the starter files and sending "http://localhost:51044/api/authors" request causes 404 error. Am I missing something or should the starter files have contained AuthorsController.cs?
Thanks...

**Comment by KevinDockx** [comment]
The controller is added during the course, in this clip: https://app.pluralsight.com/player?course=asp-dot-net-core-3-restful-api-building&author=kevin-dockx&name=05318abb-e316-44ea-a18c-2598911d5320&clip=2&mode=live
